<!DOCTYPE html>
<html>
<head>
    <title>My PDF Report</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        /* Define your CSS styles here. Inline styles or <style> blocks are generally
           more reliable than external CSS files for Dompdf. */
        body {
            font-family: sans-serif;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #333;
            font-size: 24px;
        }
        .report-details table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .report-details th, .report-details td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .report-details th {
            background-color: #f2f2f2;
        }
        .footer {
            text-align: center;
            margin-top: 50px;
            font-size: 12px;
            color: #777;
        }
        /* Custom styles for demonstration */
        .highlight {
            background-color: #fff3cd;
            padding: 5px;
            border-radius: 5px;
        }
        .text-center {
            text-align: center;
        }
        .page-break {
            page-break-after: always; /* For pagination */
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Sales Report - {{ $reportDate }}</h1>
        <p>Generated by: {{ $generatedBy }}</p>
    </div>

    <p>Dear {{ $userName }},</p>
    <p>Here is your comprehensive sales report for the period of **{{ $startDate }} to {{ $endDate }}**.</p>

    <div class="report-details">
        <h3>Summary</h3>
        <table>
            <tr>
                <th>Total Sales:</th>
                <td>${{ number_format($totalSales, 2) }}</td>
            </tr>
            <tr>
                <th>Total Orders:</th>
                <td>{{ $totalOrders }}</td>
            </tr>
            <tr>
                <th>Average Order Value:</th>
                <td>${{ number_format($averageOrderValue, 2) }}</td>
            </tr>
        </table>
    </div>

    @if (!empty($salesData))
        <div class="report-details">
            <h3>Detailed Sales Data</h3>
            <table>
                <thead>
                    <tr>
                        <th>Order ID</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Order Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($salesData as $item)
                        <tr>
                            <td>{{ $item['order_id'] }}</td>
                            <td>{{ $item['product_name'] }}</td>
                            <td>{{ $item['quantity'] }}</td>
                            <td>${{ number_format($item['price'], 2) }}</td>
                            <td>{{ $item['order_date'] }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @else
        <p class="text-center highlight">No sales data found for the specified period.</p>
    @endif

    <div class="page-break"></div> {{-- Example for a new page --}}

    <div class="report-details">
        <h3>Additional Information</h3>
        <p>This section can contain more charts, graphs, or additional textual details.</p>
        <p>For more details, please contact our support team.</p>
    </div>

    <div class="footer">
        <p>&copy; {{ date('Y') }} My Company. All rights reserved.</p>
    </div>
</body>
</html>